### ISSUE TITLE
Problems running capmon

### ISSUE THREAD

**Issue by potatochick2020** [cappe987/capmon#6]
after I follow the instruction and input 

`capmon`  or `sudo capmon`

The console produce following error

Error: insufficient permissions or kprobes not available.
Consider running with sudo or adding the capability CAP_DAC_OVERRIDE

Then I tried to add CAP_DAC_OVERRIDE+ep

` sudo setcap CAP_DAC_OVERRIDE+ep capmon`

with following error.
Failed to set capabilities on file `capmon' (No such file or directory)

May I know how should I solve it , And can I upload the readme file with your instruction in order for more clear usage guide?

**Comment by cappe987** [comment]
If running with sudo it should not be an issue of permissions. Maybe you don't have kprobe events on your system. You should find your kernel config in one of these places https://superuser.com/a/287372. Then grep for `KPROBE_EVENTS`. This worked for me `cat /boot/config-$(uname -r) | grep KPROBE_EVENTS`, but as the post says, the config may be found in different locations. If you have it installed you should find `CONFIG_KPROBE_EVENTS=y` in that file. If you do not have it installed I am not entirely sure, maybe you can load it as a module. But that might involve a lot more work.

For the second one it just sounds like you are not providing the right path. The command you provide would assume `capmon` is in the current directory. If you installed it then that's likely not the case. Do `which capmon` to find its location and try `sudo setcap cap_dac_override+ep /path/to/capmon`

**Comment by cappe987** [comment]
@potatochick2020 Do you have any update on this?

**Comment by cappe987** [comment]
Closing this issue. 

> And can I upload the readme file with your instruction in order for more clear usage guide?

There is no unclear usage in my opinion. The README specifies that it has `CONFIG_KPROBE_EVENTS` as runtime depencency, which seems to be what you are lacking from what I can tell. I could be wrong, but that error occurs because a) you don't have permission to write to the debugfs that it uses (requires elevated permissions), or b) the debugfs isn't there at all (probably because the kernel config isn't enabled).

As for `setcap`, that is another application. I might add something about it later, but otherwise refer to its own documentation.
